services:
  - type: web
    name: titanic-chatbot-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python startup.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000